apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlinx-serialization'
apply plugin: 'org.jmailen.kotlinter'

ext {
    extName = 'Nekopoi'
    pkgNameSuffix = 'id.nekopoi'
    extClass = '.Nekopoi'
    extVersionCode = 1
    libVersion = '13'
    isNsfw = true
}

apply from: "$rootDir/common.gradle"
